### PR TITLE
feat(synchronize): allow to use with void

### PR DESCRIPTION
**Pull request by 3Hren**
It is especially handy when you want to see all mutexes you own
in the backtrace.

```c++
synchronize<void> lock;

lock.apply([] {
    // Do all stuff. You'll see all locks acquired in the stack trace.
});
```

### CODE REVIEW

**Comment by antmat** [comment]
http://www.urbandictionary.com/define.php?term=zaebis

**Comment by 3Hren** [comment]
I didn't ask to TAL!

**Comment by kobolog** [comment]
What's the point except backtraces? Synchronized Void sounds like a Cyberpunk novel title.

**Comment by 3Hren** [comment]
Consistency and backtraces. Nothing except them, it's just a 50-liner PR.

**Pull request merged**
