### PR TITLE
Fix(locator): exception safety for short-living.

### PR DESCRIPTION
**Pull request by 3Hren**
Forking the session can throw which destroys current thread and terminates the program.

It can be reproduced if the client node disappears immediately after connecting.

### CODE REVIEW

**Comment by 3Hren** [comment]
Ping!

**Comment by kobolog** [comment]
Forking can't throw, sending can.

**Comment by 3Hren** [comment]
Actually it can, but not system_error.

**Comment by kobolog** [comment]
Fixed in a different commit.

**Pull request closed without merging**
