### PR TITLE
Fix(locator): acquire lock during protocol cleanup

### PR DESCRIPTION
**Pull request by 3Hren**
There is possible RC leading to SIGSEGV.

Consider:
 - Remote client has been connected.
 - Remote client disconnects (crashed).
 - Session detects RST and discarding its dispatches.
 - Session is preparing to clear its dispatches (but not cleared yet).
 - Meanwhile someone resolves some service (from other thread).
 - [1] We are here: https://github.com/cocaine/cocaine-core/blob/v0.12/src/service/locator.cpp#L469 holding iterator to `m_aggregate`.
 - Session destroys its dispatches.
 - Destructor of `connect_sink` is called.
 - We are here: https://github.com/cocaine/cocaine-core/blob/v0.12/src/service/locator.cpp#L100 and here: https://github.com/cocaine/cocaine-core/blob/v0.12/src/service/locator.cpp#L100 modifying `m_aggregates` without lock from other thread.
 - Continue [1] ...
 - Crash.

This PR fixes the given issue. Maybe there is another solution, you can resolve it other way.

### CODE REVIEW

**Comment by 3Hren** [comment]
@kobolog @antmat you are participated.

**Comment by 3Hren** [comment]
Ping-xying.

**Comment by kobolog** [comment]
I'll look into it tomorrow, hang on!

**Comment by 3Hren** [comment]
Now it's exactly the tomorrow the day after yesterday after yesterday after yesterday after yesterday after yesterday after yesterday after yesterday.

**Comment by kobolog** [comment]
Manually merged.

**Pull request closed without merging**
